trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: dnsName
    type: string
    default: <dns-name>

variables:
- group: <var-group>

steps:
  - pwsh: ./posh-acme/challange.ps1 `
          -dnsName ${{ parameters.dnsName }} `
          -esbSubscriptionKey $(esbSubscriptionKey) `
          -infobloxUser $(infobloxUser) `
          -infobloxPassword $(infobloxPassword)
    displayName: cert challange